### PR TITLE
update rpm spec to deploy UI dist files

### PR DESCRIPTION
**Pull request by brianhatchl**
refs #159

### CODE REVIEW

**Comment by sputnam** [comment]
please build rpms

**Comment by sputnam** [comment]
please build rpms

**Comment by brianhatchl** [comment]
This PR may be premature.  The hoot PR with the changes to the Makefile to build the dist files still hasn't been merged.  https://github.com/ngageoint/hootenanny/pull/1645

**Comment by sputnam** [comment]
Sounds good.  The previous errors were from some lingering local files from some work I've been doing so at least it should get past those errors for now.

**Comment by brianhatchl** [comment]
please build rpms

**Comment by brianhatchl** [comment]
please build rpms

**Comment by brianhatchl** [comment]
please build rpms

**Comment by brianhatchl** [comment]
@sputnam bump

**Pull request merged**
