### PR TITLE
Removed three occurrences of w3m

### PR DESCRIPTION
**Pull request by demmith**
Removed w3m references from hootenanny-rpms.

### CODE REVIEW

**Comment by demmith** [comment]
Reopening due to PR being closed mistakenly. All is well. :-)

**Comment by dmylov** [comment]
I closed it by mistake.  I repent and hope to be forgiven.

**Comment by sputnam** [comment]
Add to whitelist

**Comment by bmarchant** [comment]
@demmith I did a little more digging after seeing this fail and found the following in the `a2x` man page:
```
NAME
       a2x - A toolchain manager for AsciiDoc (converts Asciidoc text files to other file formats)
...
REQUISITES
       a2x uses the following programs:
       ·    Asciidoc: http://asciidoc.org/
       ·    xsltproc: (all formats except text): http://xmlsoft.org/XSLT/
       ·    DocBook XSL Stylesheets (all formats except text): http://docbook.sourceforge.net/projects/xsl/
       ·    dblatex (pdf, dvi, ps, tex formats): http://dblatex.sourceforge.net/
       ·    FOP (pdf format — alternative PDF file generator): http://xmlgraphics.apache.org/fop/
       ·    w3m (text format): http://w3m.sourceforge.net/index.en.html
       ·    Lynx (text format — alternative text file generator): http://lynx.isc.org/
       ·    epubcheck (epub format — EPUB file validator): http://code.google.com/p/epubcheck/
       See also the latest README file.
```
Our documentation is built with `asciidoc` and uses `a2x` to call other tools to create the PDF documents.  Looking at the failure for this build we should scratch this issue and PR and undo the original changes in Hootenanny also.  I can only guess that we don't build the documentation in our tests for hoot and that is why we didn't see this.

**Pull request closed without merging**
