### PR TITLE
#70 update war configs on rpm update, create tmp dir

### PR DESCRIPTION
**Pull request by brianhatchl**

### CODE REVIEW

**Comment by brianhatchl** [comment]
jenkins test this please

**Comment by brianhatchl** [comment]
jenkins test this please

**Comment by brianhatchl** [comment]
jenkins test this please

**Comment by brianhatchl** [comment]
Adds the hoot/tmp dir and also runs the war config file password replacement on update.

@mattjdnv would you review and merge?

**Comment by mattjdnv** [comment]
Done!

**Pull request merged**
