### PR TITLE
Fix FGDB build

### PR DESCRIPTION
**Pull request by bmarchant**
Esri repo changed structure so our vagrant builds that download the source zip aren't functioning correctly. This change was part of the v1.5 release. So I'm going to upgrade from v1.4 to v1.5 while I'm at it.

### CODE REVIEW

**Comment by bmarchant** [comment]
@mattjdnv very similar changes to ngageoint/hootenanny#1449

**Comment by mattjdnv** [comment]
Looks good

**Comment by bmarchant** [comment]
Jenkins please build rpms

**Comment by bmarchant** [comment]
RPM test failed because of unrelated known issue.

**Pull request merged**
