### PR TITLE
require npm for services-ui

### PR DESCRIPTION
**Pull request by brianhatchl**
refs #136

### CODE REVIEW

**Comment by brianhatchl** [comment]
please build rpms

**Comment by brianhatchl** [comment]
jenkins please build rpms

**Comment by brianhatchl** [comment]
not very robust are we jenkins?

**Comment by brianhatchl** [comment]
please build rpms

**Comment by brianhatchl** [comment]
please build rpms

**Comment by brianhatchl** [comment]
please build rpms

**Comment by sputnam** [comment]
please build rpms

**Pull request merged**
