### PR TITLE
add renderdb-export-server to rpm install

### PR DESCRIPTION
**Pull request by brianhatchl**
refs #91

### CODE REVIEW

**Comment by brianhatchl** [comment]
jenkins please build rpms

**Comment by brianhatchl** [comment]
jenkins please build rpms

**Comment by brianhatchl** [comment]
please build rpms

**Comment by sputnam** [comment]
please build rpms

**Comment by brianhatchl** [comment]
please build rpms

**Comment by brianhatchl** [comment]
please build rpms

**Comment by brianhatchl** [comment]
@sputnam this adds another nodejs server to the hoot rpm install.  would you review and merge?

**Pull request merged**
