### PR TITLE
20

### PR DESCRIPTION
**Pull request by jasonsurratt**

### CODE REVIEW

**Comment by jasonsurratt** [comment]
Jenkins, test this please.

**Comment by jasonsurratt** [comment]
Jenkins, test this please.

**Comment by brianhatchl** [comment]
From the vm, the nodesource nodejs packages are still installed:
```
[vagrant@hoot-nightly-build ~]$ sudo yum list installed | grep nodejs
nodejs.x86_64                       0.10.43-1nodesource.el6          @nodesource
nodejs-devel.x86_64                 0.10.43-1nodesource.el6          @nodesource
```

**Comment by jasonsurratt** [comment]
Those packages were installed on the base VM template. I just removed them from the template and started another test run.

**Pull request merged**
