### PR TITLE
Removed document packages

### PR DESCRIPTION
**Pull request by mattjdnv**
refs: #234 

NOTE: I'm not sure where the PDF files are getting installed. There is a docs tar archive and they are in the source archive.

### CODE REVIEW

**Comment by jbronn** [comment]
Documentation PDFs are created and included in the Hootenanny source archive (`make archive`).  As far as I can tell, that's the only time that `w3m` is needed.   However, aren't there report generation capabilities in Hootenanny core that depend on `dblatex` being available on the system?

**Comment by mattjdnv** [comment]
@jbronn The report generating code was removed a while ago. I just had another crawl through the sources and I can't find anything that uses it.

I do see the docs in the archive but I don't see them when I install the RPM's.
E.g.
```
dev:/home/dg/rpm/hootenanny-rpms $ tar -ztf SOURCES/hootenanny-0.2.42_30_g75eb592_dirty.tar.gz | grep pdf
hootenanny-0.2.42_30_g75eb592_dirty/hoot-services/src/test/resources/hoot/services/controllers/info/test_report1.pdf
hootenanny-0.2.42_30_g75eb592_dirty/test-files/test_report1.pdf
hootenanny-0.2.42_30_g75eb592_dirty/docs/Hootenanny - Algorithms.pdf
hootenanny-0.2.42_30_g75eb592_dirty/docs/Hootenanny - Developer Guide.pdf
hootenanny-0.2.42_30_g75eb592_dirty/docs/Hootenanny - Installation Instructions.pdf
hootenanny-0.2.42_30_g75eb592_dirty/docs/Hootenanny - User Guide.pdf
hootenanny-0.2.42_30_g75eb592_dirty/docs/Hootenanny - User Interface Guide.pdf
```
Installed:
```
[dev@8949e0ec967d ~]$ cd /var/lib/hootenanny/
[dev@8949e0ec967d hootenanny]$ ls -l 
total 20
drwxr-xr-x.  2 root root   24 Oct  4 18:43 bin
drwxr-xr-x.  9 root root  133 Oct  4 18:43 conf
lrwxrwxrwx.  1 root root   25 Oct  4 18:43 docs -> /usr/share/doc/hootenanny
drwxr-xr-x.  3 root root   17 Oct  4 18:43 hoot-core-test
lrwxrwxrwx.  1 root root   10 Oct  4 18:43 lib -> /usr/lib64
drwxr-xr-x.  5 root root 4096 Oct  4 18:43 plugins
drwxr-xr-x.  4 root root 4096 Oct  4 18:43 rules
drwxr-xr-x. 20 root root 4096 Oct  4 18:43 scripts
drwxr-xr-x.  3 root root 4096 Oct  4 18:43 translations
[dev@8949e0ec967d hootenanny]$ ls -l /usr/share/doc/hootenanny
ls: cannot access /usr/share/doc/hootenanny: No such file or directory
```

**Comment by jbronn** [comment]
@mattjdnv Great to hear about the report requirements removal.  The docs are in the RPMs too, but because they're marked as documentation the files are excluded by default in container installations due to `tsflags=nodocs` being set in `/etc/yum.conf` of the `centos:7` image.  On a VM you'd see:

```
$ ls -l /usr/share/doc/hootenanny
total 34636
-rw-r--r--. 1 root root       33 Sep 17 17:33 AUTHORS
-rw-r--r--. 1 root root       12 Sep 17 17:33 COPYING
-rw-r--r--. 1 root root    70293 Sep 17 17:33 GPLv3
-rw-r--r--. 1 root root  2077954 Sep 17 17:33 Hootenanny - Algorithms.pdf
-rw-r--r--. 1 root root   840941 Sep 17 17:33 Hootenanny - Developer Guide.pdf
-rw-r--r--. 1 root root   173565 Sep 17 17:33 Hootenanny - Installation Instructions.pdf
-rw-r--r--. 1 root root  2355761 Sep 17 17:33 Hootenanny - User Guide.pdf
-rw-r--r--. 1 root root 29867435 Sep 17 17:33 Hootenanny - User Interface Guide.pdf
-rw-r--r--. 1 root root       48 Sep 17 17:33 INSTALL
-rw-r--r--. 1 root root    35142 Sep 17 17:33 LICENSE
-rw-r--r--. 1 root root       14 Sep 17 17:33 README
-rw-r--r--. 1 root root     8353 Sep 17 17:33 README.md
```

**Comment by jbronn** [comment]
`yum -y --setopt tsflags= $PACKAGE` is a workaround to force documentation installation

**Pull request merged**
