### PR TITLE
Updated GDAL RPMs to build GDAL 2.1.3

### PR DESCRIPTION
**Pull request by bmarchant**
Updated GDAL.spec (and other files) to GDAL 2.1.3

### CODE REVIEW

**Comment by bmarchant** [comment]
@mattjdnv This should do it.  I've got the RPM building and hopefully everything is working right.

**Comment by bmarchant** [comment]
Jenkins please build rpms

**Comment by bmarchant** [comment]
please build rpms

**Comment by sputnam** [comment]
please build rpms

**Comment by mattjdnv** [comment]
@bmarchant   If the Update job fails, we can go back and tweak this.

**Pull request merged**
