### PR TITLE
Remove geos/gdal before installing deps

### PR DESCRIPTION
**Pull request by jasonsurratt**
1. refs https://github.com/ngageoint/hootenanny-rpms/issues/23

### CODE REVIEW

**Comment by brianhatchl** [comment]
Is this line still necessary then?
https://github.com/ngageoint/hootenanny-rpms/blob/master/src/Makefile#L33

**Comment by brianhatchl** [comment]
test this please

**Comment by brianhatchl** [comment]
test this please

**Comment by jasonsurratt** [comment]
Yes, unfortunately. https://github.com/ngageoint/hootenanny-rpms/issues/25 will make that step unnecessary.

**Comment by brianhatchl** [comment]
test this please

**Comment by brianhatchl** [comment]
test this please

**Comment by brianhatchl** [comment]
test this please

**Pull request merged**
